[build]
  command = "npm run build"

[template.environment]
  REACT_APP_SQUIDEX_URL= "Enter Squidex URL"
  REACT_APP_SQUIDEX_APPNAME= "Enter Squidex app name"
  REACT_APP_SQUIDEX_CLIENTID= "Enter Client ID for the app"
  REACT_APP_SQUIDEX_CLIENTSECRET= "Enter Client Secret for the app"
